[app]
window_geometry = "800x600"
font_family = "Arial"
font_size_main = 12
font_size_ui = 8

[llm]
provider = "ollama"
temperature = 0.7
model = "ethanwebb/OpenEuroLLM-Slovak-FIX"

[translator]
provider = "ollama"
temperature = 0.7
model = "translategemma:4b"

[data]
entries_path = "./data/entries"